export {
  useAiChats,
  usePromptApi,
  ChatHistory,
  ChatSidebar,
  PromptApi,
  PromptInput,
  type LLMAvailability,
  type LLMCreateOptions,
  type LLMCreateCoreOptions,
  type LLMProcessingState,
  type LLMPrompt,
  type LLMPromptOptions,
  type UsePromptApiOptions,
  type AiChatMessage,
  type AiChatRecord,
  type AiChatTool,
  type ChatAttachment,
  type ChatMessage,
  type ChatSidebarItem,
  type PromptAttachment,
} from '@desource/browser-ai-vue';
