export {
  useAiChats,
  usePromptApi,
  ChatHistory,
  ChatSidebar,
  PromptApi,
  PromptInput,
  type LLMAvailability,
  type LLMCreateOptions,
  type LLMCreateCoreOptions,
  type LLMContextMessageMetadata,
  type LLMContextRestorePhase,
  type LLMContextRestoreState,
  type LLMContextSummaryMode,
  type LLMContextSummaryRecord,
  type LLMContextStrategy,
  type LLMProcessingState,
  type LLMPrompt,
  type LLMPromptOptions,
  type LLMRestoreSessionOptions,
  type LLMRestoreSessionResult,
  type LLMTemporaryPromptOptions,
  type UsePromptApiOptions,
  type AiChatMessage,
  type AiChatRecord,
  type AiChatSummaryRecord,
  type AiChatTool,
  type ChatAttachment,
  type ChatMessage,
  type ChatSidebarItem,
  type PromptAttachment,
} from '@desource/browser-ai-vue';
